name: flake-check
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: |
          set -e
          nix flake check ./dev --print-build-logs --no-update-lock-file --override-input flake-file github:$GITHUB_REPOSITORY/$GITHUB_SHA
          ( 
            cd templates/default
            git init
            git add .
            nix flake check --print-build-logs --no-update-lock-file --override-input flake-file github:$GITHUB_REPOSITORY/$GITHUB_SHA
            rm -rf .git
          )
